script["a7544"] = [f(s.speak, who=["paulinchen"])] #t
script["a12105"] = [f(s.stop, who=["paulinchen"])] #z
script["a36257"] = [f(s.speak, who=["paulinchen"])] #t
script["a54675"] = [f(s.stop, who=["paulinchen"])] #z
script["a55260"] = [f(s.speak, who=["paulinchen"])] #t
script["a64207"] = [f(s.stop, who=["paulinchen"])] #z
script["a64540"] = [f(s.speak, who=["paulinchen"])] #t
script["a68829"] = [f(s.stop, who=["paulinchen"])] #z
script["a69367"] = [f(s.speak, who=["paulinchen"])] #t
script["a71676"] = [f(s.stop, who=["paulinchen"])] #z
script["a74033"] = [f(s.speak, who=["paulinchen"])] #t
script["a78336"] = [f(s.stop, who=["paulinchen"])] #z
script["a78636"] = [f(s.speak, who=["paulinchen"])] #t
script["a82966"] = [f(s.stop, who=["paulinchen"])] #z
script["a85548"] = [f(s.speak, who=["paulinchen"])] #t
script["a103832"] = [f(s.stop, who=["paulinchen"])] #z
script["a104060"] = [f(s.speak, who=["paulinchen"])] #t
script["a113844"] = [f(s.stop, who=["paulinchen"])] #z
script["a113980"] = [f(s.speak, who=["paulinchen"])] #t
script["a132446"] = [f(s.stop, who=["paulinchen"])] #z
script["a133050"] = [f(s.speak, who=["paulinchen"])] #t
script["a135385"] = [f(s.stop, who=["paulinchen"])] #z
script["a135728"] = [f(s.speak, who=["paulinchen"])] #t
script["a136921"] = [f(s.stop, who=["paulinchen"])] #z
script["a137269"] = [f(s.speak, who=["paulinchen"])] #t
script["a141888"] = [f(s.stop, who=["paulinchen"])] #z
script["a142118"] = [f(s.speak, who=["paulinchen"])] #t
script["a144672"] = [f(s.stop, who=["paulinchen"])] #z
script["a145010"] = [f(s.speak, who=["paulinchen"])] #t
script["a146916"] = [f(s.stop, who=["paulinchen"])] #z
script["a147105"] = [f(s.speak, who=["paulinchen"])] #t
script["a151464"] = [f(s.stop, who=["paulinchen"])] #z
script["a187486"] = [f(s.speak, who=["paulinchen"])] #t
script["a189171"] = [f(s.stop, who=["paulinchen"])] #z
script["a200827"] = [f(s.speak, who=["paulinchen"])] #t
script["a229842"] = [f(s.stop, who=["paulinchen"])] #z
script["a230579"] = [f(s.speak, who=["paulinchen"])] #t
script["a244481"] = [f(s.stop, who=["paulinchen"])] #z
