script[37222] = [f(fx.set_back_rgb, values=fx.blue(), update=True, autoOff=False)] #n
script[37321] = [f(fx.set_back_rgb, values=fx.red(), update=True, autoOff=False)] #c
script[37532] = [f(fx.set_back_rgb, values=fx.blue(), update=True, autoOff=False)] #n
script[38160] = [f(fx.set_back_rgb, values=fx.red(), update=True, autoOff=False)] #n
script[38354] = [f(fx.set_back_rgb, values=fx.green(), update=True, autoOff=False)] #c
script[38502] = [f(fx.set_back_rgb, values=fx.blue(), update=True, autoOff=False)] #n
script[39018] = [f(fx.set_back_rgb, values=fx.red(), update=True, autoOff=False)] #n
script[39238] = [f(fx.set_back_rgb, values=fx.blue(), update=True, autoOff=False)] #n
script[39388] = [f(fx.set_back_rgb, values=fx.green(), update=True, autoOff=False)] #c
script[39889] = [f(fx.set_back_rgb, values=fx.red(), update=True, autoOff=False)] #n
script[40201] = [f(fx.set_back_rgb, values=fx.green(), update=True, autoOff=False)] #c
